dist: trusty
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly

allow_failures:
  - php: nightly

# Use new container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

install:
  # Setup the test server
  - composer install --no-interaction
  - phpenv local --unset

  # Environment checks
  - phpunit --version
  - phpcs --version

  # Install & update Snyk.io vulnerability testing
  - npm install -g snyk
  - snyk monitor --file=composer.lock
  - snyk monitor --file=package.json

script:
  - phpunit --coverage-clover=coverage.xml
  - phpcs -s

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Snyk.io vulnerability checks
  - snyk test --file=package.json
  - snyk test --file=composer.lock

